---
- hosts: localhost
  connection: local
  become: true
  vars:
    ansible_user_id: "garchomp"

  pre_tasks:
    - name: update repository index (Debian)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == "Debian"

  tasks:
    -include:
      - tasks/packages.yml
      - tasks/zsh.yml
