- hosts: localhost
  connection: local
  become: true
  vars:
    ansible_user_id: "garchomp"

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/nvm.yml
    - include_tasks: tasks/docker.yml
