- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update repository index (Debian)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution_family == "Debian"
