- name: Install packages
  become: yes
  apt:
    name:
      - htop
      - stow
      - python3-pip
      - pipx
      - openssh-server
      - git 
      - neofetch
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: yes