- name: Install zsh
  tags: zsh, rahul
  become: true
  apt:
    - zsh
  state: present
  update_cache: yes

- name: Install fzf
  become: true
  apt: 
    fzf
  state: present
  update_cache: yes

- name: Install Oh-my-ZSH
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: ~/.oh-my-zsh
    depth: 1

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Copy zshrc file 
  ansible.builtin.copy:
    src: /files/zhsrc
    dest: /home/{{ ansible_user_id }}/.zshrc
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'